name: Basic CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Start the dev server
        run: |
          npm run dev &
          npx wait-on http://localhost:3000

      - name: Run unit tests
        run: |
          npm run test

      - name: Run Playwright tests
        run: |
          npx playwright install
          npx playwright test

      - name: Build the project
        run: |
          npm run build

      - name: Generate coverage report
        run: |
          npx vitest --coverage
